/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author myoss
 */
public class VisaCard extends javax.swing.JFrame {

    /**
     * Creates new form VisaCard
     */
    public VisaCard() {
        initComponents();
        System s=new System();
        try {
            s.getVise();
        Cardid.setText(String.valueOf(s.getUser_id()));
        name.setText(s.getUser_name());
        password.setText(String.valueOf(s.getPassword()));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        Cardid = new javax.swing.JTextField();
        signUp1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(451, 301));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 300));
        getContentPane().setLayout(null);

        label.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        label.setText("Card ID: ");
        getContentPane().add(label);
        label.setBounds(30, 20, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Password : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 150, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Name : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 80, 110, 40);

        name.setEditable(false);
        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(name);
        name.setBounds(170, 90, 200, 40);

        password.setEditable(false);
        password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(password);
        password.setBounds(170, 160, 200, 40);

        Cardid.setEditable(false);
        Cardid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Cardid);
        Cardid.setBounds(170, 20, 200, 40);

        signUp1.setBackground(new java.awt.Color(255, 102, 255));
        signUp1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        signUp1.setText("Sign in");
        signUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUp1ActionPerformed(evt);
            }
        });
        getContentPane().add(signUp1);
        signUp1.setBounds(140, 230, 130, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/rsz_1visa_bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUp1ActionPerformed
        // TODO add your handling code here:
                LogIn view =new LogIn();
         view.setVisible(true);
         view.setLocation(300, 100);
         this.dispose();
    }//GEN-LAST:event_signUp1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cardid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label;
    private javax.swing.JTextField name;
    private javax.swing.JTextField password;
    private javax.swing.JButton signUp1;
    // End of variables declaration//GEN-END:variables
}
